In [1]:
import pandas as pd
import sqlite3

In [2]:
data_path = "./olist/" # path of csv files

In [3]:
conn = sqlite3.connect("olist.db") # will automatically create the database 'olist.db'

In [4]:
def load_csv(table_name, file_name):
    df = pd.read_csv(data_path + file_name)
    df.to_sql(table_name, conn, if_exists = "replace", index = False)
    print(f"{table_name}: {len(df)} rows loaded")

In [5]:
load_csv("customers", "olist_customers_dataset.csv")
load_csv("location", "olist_geolocation_dataset.csv")
load_csv("order_items", "olist_order_items_dataset.csv")
load_csv("payments", "olist_order_payments_dataset.csv")
load_csv("reviews", "olist_order_reviews_dataset.csv")
load_csv("orders", "olist_orders_dataset.csv")
load_csv("product", "olist_products_dataset.csv")
load_csv("seller", "olist_sellers_dataset.csv")
load_csv("product_category", "product_category_name_translation.csv")

customers: 99441 rows loaded
location: 1000163 rows loaded
order_items: 112650 rows loaded
payments: 103886 rows loaded
reviews: 99224 rows loaded
orders: 99441 rows loaded
product: 32951 rows loaded
seller: 3095 rows loaded
product_category: 71 rows loaded

In [6]:
pd.read_sql("SELECT name FROM sqlite_master WHERE type = 'table'", conn)

               name
0         customers
1          location
2       order_items
3          payments
4           reviews
5            orders
6           product
7            seller
8  product_category

In [7]:
pd.read_sql('''SELECT (SELECT COUNT(*) FROM customers) AS customers,
                      (SELECT COUNT(*) FROM orders) AS orders,
                      (SELECT COUNT(*) FROM payments) AS payments
                      ''', conn)

   customers  orders  payments
0      99441   99441    103886

In [8]:
pd.read_sql('''SELECT COUNT(DISTINCT customer_id) AS id FROM customers''', conn)

      id
0  99441

In [9]:
conn.close()